import type { ReactNode } from "react";
import "./globals.css";
import type { Metadata } from "next";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body
				className={`font-sans antialiased bg-background text-secondary dark`}
			>
				<Sidebar />
				<main className="ml-56 flex-1 p-4">
					{children}
				</main>
			</body>
		</html>
	);
}
